/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresacashescritorio.capa1_presentacion;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio Aburto Cortez
 */
public class FormMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuPrincipal
     */
    public static int anchoPantalla = 0, alturaPantalla = 0;

    public FormMenuPrincipal() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        fullScreen();
    }

    public void fullScreen() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension miPantalla = tk.getScreenSize();
        anchoPantalla = miPantalla.width;
        alturaPantalla = miPantalla.height;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fiveCodMaterialPanel1 = new FiveCodMaterialDesignPanel.FiveCodMaterialPanel();
        jLabel1 = new javax.swing.JLabel();
        fiveCodLabelImage1 = new fivecodlabelimage.FiveCodLabelImage();
        btnRegistroAFP = new FiveCodMaterialDesignButton.FiveCodMaterialButton();
        fiveCodMaterialPanel2 = new FiveCodMaterialDesignPanel.FiveCodMaterialPanel();
        jLabel2 = new javax.swing.JLabel();
        fiveCodLabelImage2 = new fivecodlabelimage.FiveCodLabelImage();
        btnRegistroAFP1 = new FiveCodMaterialDesignButton.FiveCodMaterialButton();
        fiveCodMaterialPanel3 = new FiveCodMaterialDesignPanel.FiveCodMaterialPanel();
        jLabel3 = new javax.swing.JLabel();
        fiveCodLabelImage3 = new fivecodlabelimage.FiveCodLabelImage();
        btnRegistroAFP2 = new FiveCodMaterialDesignButton.FiveCodMaterialButton();
        fiveCodMaterialPanel4 = new FiveCodMaterialDesignPanel.FiveCodMaterialPanel();
        jLabel4 = new javax.swing.JLabel();
        fiveCodLabelImage4 = new fivecodlabelimage.FiveCodLabelImage();
        btnRegistroAFP3 = new FiveCodMaterialDesignButton.FiveCodMaterialButton();
        fiveCodMaterialPanel5 = new FiveCodMaterialDesignPanel.FiveCodMaterialPanel();
        jLabel5 = new javax.swing.JLabel();
        fiveCodLabelImage5 = new fivecodlabelimage.FiveCodLabelImage();
        btnRegistroAFP4 = new FiveCodMaterialDesignButton.FiveCodMaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tipo cliente");

        btnRegistroAFP.setBackground(new java.awt.Color(65, 94, 255));
        btnRegistroAFP.setBorder(null);
        btnRegistroAFP.setText("Registro");
        btnRegistroAFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAFPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fiveCodMaterialPanel1Layout = new javax.swing.GroupLayout(fiveCodMaterialPanel1);
        fiveCodMaterialPanel1.setLayout(fiveCodMaterialPanel1Layout);
        fiveCodMaterialPanel1Layout.setHorizontalGroup(
            fiveCodMaterialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel1Layout.createSequentialGroup()
                .addGroup(fiveCodMaterialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fiveCodMaterialPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(fiveCodMaterialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(fiveCodLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fiveCodMaterialPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnRegistroAFP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        fiveCodMaterialPanel1Layout.setVerticalGroup(
            fiveCodMaterialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fiveCodLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroAFP, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(fiveCodMaterialPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, 198));

        jLabel2.setText("CLIENTE");

        btnRegistroAFP1.setBackground(new java.awt.Color(65, 94, 255));
        btnRegistroAFP1.setBorder(null);
        btnRegistroAFP1.setText("Registro");
        btnRegistroAFP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAFP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fiveCodMaterialPanel2Layout = new javax.swing.GroupLayout(fiveCodMaterialPanel2);
        fiveCodMaterialPanel2.setLayout(fiveCodMaterialPanel2Layout);
        fiveCodMaterialPanel2Layout.setHorizontalGroup(
            fiveCodMaterialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel2Layout.createSequentialGroup()
                .addGroup(fiveCodMaterialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fiveCodMaterialPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistroAFP1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fiveCodMaterialPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(fiveCodMaterialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(fiveCodLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fiveCodMaterialPanel2Layout.setVerticalGroup(
            fiveCodMaterialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(fiveCodLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistroAFP1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(fiveCodMaterialPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 88, -1, 181));

        jLabel3.setText("GRUPO");

        btnRegistroAFP2.setBackground(new java.awt.Color(65, 94, 255));
        btnRegistroAFP2.setBorder(null);
        btnRegistroAFP2.setText("Registro");
        btnRegistroAFP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAFP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fiveCodMaterialPanel3Layout = new javax.swing.GroupLayout(fiveCodMaterialPanel3);
        fiveCodMaterialPanel3.setLayout(fiveCodMaterialPanel3Layout);
        fiveCodMaterialPanel3Layout.setHorizontalGroup(
            fiveCodMaterialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel3Layout.createSequentialGroup()
                .addGroup(fiveCodMaterialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fiveCodMaterialPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistroAFP2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fiveCodMaterialPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(fiveCodMaterialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(fiveCodLabelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        fiveCodMaterialPanel3Layout.setVerticalGroup(
            fiveCodMaterialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fiveCodLabelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistroAFP2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(fiveCodMaterialPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 71, -1, -1));

        jLabel4.setText("Prestamo");

        btnRegistroAFP3.setBackground(new java.awt.Color(65, 94, 255));
        btnRegistroAFP3.setBorder(null);
        btnRegistroAFP3.setText("Registro");
        btnRegistroAFP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAFP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fiveCodMaterialPanel4Layout = new javax.swing.GroupLayout(fiveCodMaterialPanel4);
        fiveCodMaterialPanel4.setLayout(fiveCodMaterialPanel4Layout);
        fiveCodMaterialPanel4Layout.setHorizontalGroup(
            fiveCodMaterialPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel4Layout.createSequentialGroup()
                .addGroup(fiveCodMaterialPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fiveCodMaterialPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistroAFP3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fiveCodMaterialPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(fiveCodMaterialPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(fiveCodLabelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        fiveCodMaterialPanel4Layout.setVerticalGroup(
            fiveCodMaterialPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(fiveCodLabelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistroAFP3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(fiveCodMaterialPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel5.setText("Descripcion Prestamo");

        btnRegistroAFP4.setBackground(new java.awt.Color(65, 94, 255));
        btnRegistroAFP4.setBorder(null);
        btnRegistroAFP4.setText("Registro");
        btnRegistroAFP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAFP4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fiveCodMaterialPanel5Layout = new javax.swing.GroupLayout(fiveCodMaterialPanel5);
        fiveCodMaterialPanel5.setLayout(fiveCodMaterialPanel5Layout);
        fiveCodMaterialPanel5Layout.setHorizontalGroup(
            fiveCodMaterialPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel5Layout.createSequentialGroup()
                .addGroup(fiveCodMaterialPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fiveCodMaterialPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(fiveCodLabelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fiveCodMaterialPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(fiveCodMaterialPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnRegistroAFP4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fiveCodMaterialPanel5Layout.setVerticalGroup(
            fiveCodMaterialPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveCodMaterialPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(fiveCodLabelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistroAFP4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(fiveCodMaterialPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(764, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroAFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAFPActionPerformed

        FormGestionarTipoCliente d = new FormGestionarTipoCliente(this, true);
        d.setBounds(0, 30, anchoPantalla, alturaPantalla - 70);
        d.setVisible(true);

    }//GEN-LAST:event_btnRegistroAFPActionPerformed

    private void btnRegistroAFP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAFP1ActionPerformed
        FormGestionarCliente d = new FormGestionarCliente(this, true);
        d.setBounds(0, 30, anchoPantalla, alturaPantalla - 70);
        d.setVisible(true);
    }//GEN-LAST:event_btnRegistroAFP1ActionPerformed

    private void btnRegistroAFP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAFP2ActionPerformed
        FormRegistrarGrupo d = new FormRegistrarGrupo(this, true);
        d.setBounds(0, 30, anchoPantalla, alturaPantalla - 70);
        d.setVisible(true);
    }//GEN-LAST:event_btnRegistroAFP2ActionPerformed

    private void btnRegistroAFP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAFP3ActionPerformed
        FormGestionarPrestamo d = new FormGestionarPrestamo(this, true);
        d.setVisible(true);
    }//GEN-LAST:event_btnRegistroAFP3ActionPerformed

    private void btnRegistroAFP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAFP4ActionPerformed
        FormPlantilla d = new FormPlantilla(this, true);
        d.setBounds(0, 30, anchoPantalla, alturaPantalla - 70);
        d.setVisible(true);
    }//GEN-LAST:event_btnRegistroAFP4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormMenuPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FiveCodMaterialDesignButton.FiveCodMaterialButton btnRegistroAFP;
    private FiveCodMaterialDesignButton.FiveCodMaterialButton btnRegistroAFP1;
    private FiveCodMaterialDesignButton.FiveCodMaterialButton btnRegistroAFP2;
    private FiveCodMaterialDesignButton.FiveCodMaterialButton btnRegistroAFP3;
    private FiveCodMaterialDesignButton.FiveCodMaterialButton btnRegistroAFP4;
    private fivecodlabelimage.FiveCodLabelImage fiveCodLabelImage1;
    private fivecodlabelimage.FiveCodLabelImage fiveCodLabelImage2;
    private fivecodlabelimage.FiveCodLabelImage fiveCodLabelImage3;
    private fivecodlabelimage.FiveCodLabelImage fiveCodLabelImage4;
    private fivecodlabelimage.FiveCodLabelImage fiveCodLabelImage5;
    private FiveCodMaterialDesignPanel.FiveCodMaterialPanel fiveCodMaterialPanel1;
    private FiveCodMaterialDesignPanel.FiveCodMaterialPanel fiveCodMaterialPanel2;
    private FiveCodMaterialDesignPanel.FiveCodMaterialPanel fiveCodMaterialPanel3;
    private FiveCodMaterialDesignPanel.FiveCodMaterialPanel fiveCodMaterialPanel4;
    private FiveCodMaterialDesignPanel.FiveCodMaterialPanel fiveCodMaterialPanel5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
