/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresacashescritorio.capa1_presentacion;

import empresacashescritorio.capa1_presentacion.util.Mensaje;
import empresacashescritorio.capa1_presentacion.util.Verificador;
import empresacashescritorio.capa2_aplicacion.GestionarTipoClienteServicio;
import empresacashescritorio.capa2_aplicacion.RegistrarPrestamoServicio;
import empresacashescritorio.capa3_dominio.Prestamo;
import empresacashescritorio.capa3_dominio.TipoCliente;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import mastersoft.modelo.ModeloTabla;
import mastersoft.tabladatos.Columna;
import mastersoft.tabladatos.Fila;
import mastersoft.tabladatos.Tabla;

/**
 *
 * @author Antonio Aburto Cortez
 */
public class FormGestionarPrestamo extends javax.swing.JDialog {

    /**
     * Creates new form FormGestionarEmpleado
     */
    private RegistrarPrestamoServicio registrarPrestamoServicio;
    private List<Prestamo> listaPrestamo = null;
    private int filaSeleccionada = -1;

    public FormGestionarPrestamo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            popMenu.add(pnlMenu);
            registrarPrestamoServicio = new RegistrarPrestamoServicio();
            inicializarTablaColumnas();
            llenarDatosGeneral();
            enabledButton(true);
        } catch (Exception e) {
            Mensaje.mostrarAdvertencia(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btn_Modificar = new fivecodbutton.FiveCodButton();
        btn_Eliminar = new fivecodbutton.FiveCodButton();
        btn_pagar = new fivecodbutton.FiveCodButton();
        popMenu = new javax.swing.JPopupMenu();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btn_crear = new fivecodbutton.FiveCodButton();
        btn_buscar = new fivecodbutton.FiveCodButton();
        txt_dniCliente = new org.jdesktop.swingx.JXSearchField();
        btn_procesarPago = new fivecodbutton.FiveCodButton();
        btn_cancelar = new fivecodbutton.FiveCodButton();
        btn_modificarPrestamo = new fivecodbutton.FiveCodButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_DatosAFP = new FiveCodTable.FiveCodJTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fiveCodButton1 = new fivecodbutton.FiveCodButton();

        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Modificar.setBackground(new java.awt.Color(65, 94, 255));
        btn_Modificar.setText("MODIFICAR");
        btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        btn_Eliminar.setBackground(new java.awt.Color(65, 94, 255));
        btn_Eliminar.setText("ELIMINAR");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 30));

        btn_pagar.setBackground(new java.awt.Color(65, 94, 255));
        btn_pagar.setText("PROCESAR PAGO");
        btn_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagarActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 30));

        popMenu.setBackground(new java.awt.Color(65, 94, 255));
        popMenu.setForeground(new java.awt.Color(65, 94, 255));
        popMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 94, 255), 2));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel8.setBorder(dropShadowBorder1);

        btn_crear.setBackground(new java.awt.Color(65, 94, 255));
        btn_crear.setText("CREAR");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(65, 94, 255));
        btn_buscar.setColorHover(new java.awt.Color(253, 173, 1));
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        txt_dniCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(65, 94, 255)));
        txt_dniCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_dniCliente.setPrompt("INGRESE DNI DEL EMPLEADO");
        txt_dniCliente.setPromptFontStyle(new java.lang.Integer(4));
        txt_dniCliente.setPromptForeground(new java.awt.Color(65, 94, 255));
        txt_dniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dniClienteActionPerformed(evt);
            }
        });
        txt_dniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_dniClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dniClienteKeyTyped(evt);
            }
        });

        btn_procesarPago.setBackground(new java.awt.Color(65, 94, 255));
        btn_procesarPago.setText("PROCESAR PAGO");
        btn_procesarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarPagoActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(65, 94, 255));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_modificarPrestamo.setBackground(new java.awt.Color(65, 94, 255));
        btn_modificarPrestamo.setText("MODIFICAR");
        btn_modificarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_modificarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_procesarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(txt_dniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_procesarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        tabla_DatosAFP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_DatosAFP.setGrosorBordeFilas(0);
        tabla_DatosAFP.setGrosorBordeHead(0);
        tabla_DatosAFP.setRowHeight(20);
        tabla_DatosAFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_DatosAFPMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_DatosAFP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(65, 94, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GESTIONAR DATOS DEL CONTRATO");

        fiveCodButton1.setBackground(new java.awt.Color(65, 94, 255));
        fiveCodButton1.setBorder(null);
        fiveCodButton1.setColorHover(new java.awt.Color(255, 68, 68));
        fiveCodButton1.setFont(new java.awt.Font("Roboto Bold", 1, 20)); // NOI18N
        fiveCodButton1.setLabel("X");
        fiveCodButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveCodButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(fiveCodButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addComponent(fiveCodButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(1038, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        crearPrestamo();
    }//GEN-LAST:event_btn_crearActionPerformed

    private void crearPrestamo() {
        try {
            VentanaPrestamoCrear f = new VentanaPrestamoCrear(null, true);
            f.setVisible(true);
            llenarDatosGeneral();
        } catch (Exception e) {
        }
    }

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMover.FiveCodMoverJDialog.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMover.FiveCodMoverJDialog.MouseDraggedJDialog(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void fiveCodButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveCodButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_fiveCodButton1ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        buscarPrestamo();

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void buscarPrestamo() {
        try {

            String dni = txt_dniCliente.getText().toString();
            if (!dni.equals("")) {
                listaPrestamo = registrarPrestamoServicio.buscarPorLike(dni);
                llenarDatosTabla();
            } else {
                llenarDatosGeneral();
            }

        } catch (Exception e) {
        }
    }

    private void txt_dniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dniClienteActionPerformed

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarActionPerformed
        modificarPrestamo();
    }//GEN-LAST:event_btn_ModificarActionPerformed

    private void modificarPrestamo() {
        try {

            Prestamo prestamo = buscarPrestamo((int) tabla_DatosAFP.getValueAt(filaSeleccionada, 0));
            registrarPrestamoServicio.sePuedeModificar(prestamo);
            VentanaPrestamoCrear ventanaDatosAFP = new VentanaPrestamoCrear(null, true, prestamo);
            ventanaDatosAFP.setVisible(true);
            llenarDatosGeneral();
        } catch (Exception e) {
            Mensaje.mostrarAdvertencia(e.getMessage());
        }
    }

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed

        eliminarPrestamo();

    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void eliminarPrestamo() {
        try {
            if (filaSeleccionada != -1) {
                Prestamo prestamo = buscarPrestamo((int) tabla_DatosAFP.getValueAt(filaSeleccionada, 0));
                registrarPrestamoServicio.sePuedeEliminar(prestamo);
                int indice = JOptionPane.showConfirmDialog(this, "Desea eliminar", "FiveCod: Pregunta", JOptionPane.YES_NO_OPTION);
                if (indice == 1) {
                    return;
                }
                try {
                    int registros_afectados = registrarPrestamoServicio.eliminar(prestamo.getId());
                    if (registros_afectados == 1) {
                        Mensaje.mostrarAfirmacionDeEliminacion();
                        llenarDatosTabla();
                    } else {
                        Mensaje.mostrarErrorDeEliminacion();
                    }

                } catch (Exception e) {
                    Mensaje.mostrarAdvertenciaDeEliminacion();
                }

            } else {
                Mensaje.mostrarFilaNoSeleccionada();
            }
        } catch (Exception e) {
            Mensaje.mostrarAdvertencia(e.getMessage());
        }
    }

    private void btn_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagarActionPerformed
        pagarPrestamo();
    }//GEN-LAST:event_btn_pagarActionPerformed

    private void tabla_DatosAFPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_DatosAFPMousePressed
        filaSeleccionada = tabla_DatosAFP.getSelectedRow();
        enabledButton(false);
    }//GEN-LAST:event_tabla_DatosAFPMousePressed

    private void txt_dniClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dniClienteKeyReleased
        buscarPrestamo();
    }//GEN-LAST:event_txt_dniClienteKeyReleased

    private void txt_dniClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dniClienteKeyTyped
        Verificador.verificarNumeros(evt, txt_dniCliente, 8);
    }//GEN-LAST:event_txt_dniClienteKeyTyped

    private void btn_procesarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarPagoActionPerformed
        pagarPrestamo();
    }//GEN-LAST:event_btn_procesarPagoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        enabledButton(true);

    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_modificarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarPrestamoActionPerformed
        modificarPrestamo();
    }//GEN-LAST:event_btn_modificarPrestamoActionPerformed

    private void pagarPrestamo() {
        try {
            Prestamo prestamo = buscarPrestamo((int) tabla_DatosAFP.getValueAt(filaSeleccionada, 0));
            registrarPrestamoServicio.sePuedeModificar(prestamo);
            VentanaPrestamoPagar ventanaDatosAFP = new VentanaPrestamoPagar(null, true, prestamo);
            ventanaDatosAFP.setVisible(true);
            llenarDatosGeneral();
        } catch (Exception e) {
            Mensaje.mostrarAdvertencia(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fivecodbutton.FiveCodButton btn_Eliminar;
    private fivecodbutton.FiveCodButton btn_Modificar;
    private fivecodbutton.FiveCodButton btn_buscar;
    private fivecodbutton.FiveCodButton btn_cancelar;
    private fivecodbutton.FiveCodButton btn_crear;
    private fivecodbutton.FiveCodButton btn_modificarPrestamo;
    private fivecodbutton.FiveCodButton btn_pagar;
    private fivecodbutton.FiveCodButton btn_procesarPago;
    private fivecodbutton.FiveCodButton fiveCodButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPopupMenu popMenu;
    private FiveCodTable.FiveCodJTable tabla_DatosAFP;
    private org.jdesktop.swingx.JXSearchField txt_dniCliente;
    // End of variables declaration//GEN-END:variables

    //metodos 
    private void enabledButton(boolean estado) {
        btn_crear.setEnabled(estado);
        btn_modificarPrestamo.setEnabled(!estado);
        btn_procesarPago.setEnabled(!estado);
        btn_cancelar.setBackground(new Color(255, 82, 54));
        if (estado) {
            btn_crear.setBackground(new Color(255, 82, 54));
            pintarBoton(new Color(65, 94, 255));
        } else {
            pintarBoton(new Color(255, 82, 54));
            btn_crear.setBackground(new Color(65, 94, 255));

        }
    }

    private Prestamo buscarPrestamo(int codigo) {
        Prestamo prestamoEncontrado = null;
        for (Prestamo prestamo : listaPrestamo) {
            if (prestamo.getId() == codigo) {
                prestamoEncontrado = prestamo;
            }
        }
        return prestamoEncontrado;
    }

    private void inicializarTablaColumnas() {
        Tabla tabla = new Tabla();
        tabla.agregarColumna(new Columna("Codigo", "java.lang.Integer"));
        tabla.agregarColumna(new Columna("CLIENTE", "java.lang.String"));
        tabla.agregarColumna(new Columna("DNI", "java.lang.String"));

        tabla.agregarColumna(new Columna("F INICIO", "java.lang.String"));
        tabla.agregarColumna(new Columna("F FIN", "java.lang.String"));
        tabla.agregarColumna(new Columna("F PAGO", "java.lang.String"));
        tabla.agregarColumna(new Columna("MONTO S/.", "java.lang.String"));
        tabla.agregarColumna(new Columna("COMISIÓN S/.", "java.lang.String"));
        tabla.agregarColumna(new Columna("TOTAL S/.", "java.lang.String"));

        tabla.agregarColumna(new Columna("ESTADO", "java.lang.String"));

        ModeloTabla modeloTabla = new ModeloTabla(tabla);
        tabla_DatosAFP.setModel(modeloTabla);
        tabla_DatosAFP.getColumn(tabla_DatosAFP.getColumnName(0)).setWidth(0);
        tabla_DatosAFP.getColumn(tabla_DatosAFP.getColumnName(0)).setMinWidth(0);
        tabla_DatosAFP.getColumn(tabla_DatosAFP.getColumnName(0)).setMaxWidth(0);
    }

    private void llenarDatosGeneral() {
        try {
            listaPrestamo = registrarPrestamoServicio.mostrar();
            llenarDatosTabla();
        } catch (Exception e) {
            Mensaje.mostrarAdvertencia(e.getMessage());

        }

    }

    private void llenarDatosTabla() throws Exception {

        Fila filaTabla;
        try {
            ModeloTabla modeloTabla = (ModeloTabla) tabla_DatosAFP.getModel();
            modeloTabla.eliminarTotalFilas();
            if (listaPrestamo.size() == 0) {
                Mensaje.mostrarAdvertenciaSinElementos();
            } else {
                for (Prestamo prestamo : listaPrestamo) {
                    filaTabla = new Fila();
                    filaTabla.agregarValorCelda(prestamo.getId());
                    filaTabla.agregarValorCelda(prestamo.getCliente().generaNombre());
                    filaTabla.agregarValorCelda(prestamo.getCliente().getDni());
                    filaTabla.agregarValorCelda(prestamo.getFechaInicio());
                    filaTabla.agregarValorCelda(prestamo.getFechaFin());
                    filaTabla.agregarValorCelda(prestamo.getFechaPago());
                    filaTabla.agregarValorCelda(prestamo.getMonto());
                    filaTabla.agregarValorCelda(prestamo.calcularComision());
                    filaTabla.agregarValorCelda(prestamo.calcularTotal());
                    filaTabla.agregarValorCelda(prestamo.getEstado());

                    modeloTabla.agregarFila(filaTabla);
                }
                modeloTabla.refrescarDatos();
            }

        } catch (Exception e) {
            Mensaje.mostrarErrorSistema();
        }

    }

    private void pintarBoton(Color color) {
        btn_modificarPrestamo.setBackground(color);
        btn_procesarPago.setBackground(color);
    }

}
